### ISSUE TITLE
Why did you use a ContinuousActor?

### ISSUE THREAD

**Issue by CAI23sbP** [jhejna/cpl#14]
Hi @jhejna  i read your paper, it was very interesting to me.
By the way, i saw your code. It used the ContinuousMLPActor for Actor network.
It means that action is not came from distribution like GaussianDistribution.
Why did you use a MLP Actor? Because of CPL's theory?
  
But in a CPL and its' variants considered distribution like under code. Its' mean it is okay to use a Distribution?
![image](https://github.com/jhejna/cpl/assets/108871750/484dfeef-7547-4899-8ea2-059eb5b1c4b6)

**Comment by jhejna** [comment]
You can use either! We didn't observe a difference in performance for MetaWorld, but saw slightly better performance in D4RL when using a Gaussian Distribution with a per-dimension variance.

Both actor types are gaussian. The ContinuousMLPActor is just an isotropic gaussian.

**Comment by CAI23sbP** [comment]
thank you for your reply!.
