### ISSUE TITLE
Inquiry About Reproduction Details of D.5 Section in the CPL Appendix

### ISSUE THREAD

**Issue by Cookie-Crisp** [jhejna/cpl#15]
Hi,

Thank you for sharing this great work! I’m trying to reproduce the results from Appendix D.5, specifically the D4RL experiments. Could you please provide more details about the dataset and model parameters used in this part? For example:

Any preprocessing steps applied to the D4RL dataset.
The exact model architecture and hyperparameter settings.
Your guidance would be immensely helpful. Thank you in advance!

**Comment by jhejna** [comment]
Hi! I just updated the README to link to the repo we used for these experiments. Sorry it was missing originally! The code is found here https://github.com/jhejna/cpl-human and was open-sourced a while ago.

**Comment by Cookie-Crisp** [comment]
Thank you for your reply！
