### ISSUE TITLE
pip install -e research error.

### ISSUE THREAD

**Issue by EchoSilverLining** [jhejna/cpl#3]

**Comment by charlesxu90** [comment]
Same problem
```text
cpl/research does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

Solved by running the following command in the cpl folder:
```shell
pip install -e .
```

**Comment by jhejna** [comment]
Marking as resolved -- the correct solution should be `pip install -e .`, apologies for the mistake in documentation.
