### ISSUE TITLE
[Bug?]: Questions about the TD target calculation in P-IQL

### ISSUE THREAD

**Issue by typoverflow** [jhejna/cpl#4]
Hi all, 
It seems that the termination flag is missing when calculating the TD target for  P-IQL. The correct calculation should be `target = reward + discount*(1-done)*next_v`. However, in the datasets you provide, the `done` flag is incomplete so I was not able to fix this problem (regenerating the dataset is also impossible since I don't have access to the behavior policy checkpoints.). Is there anything I have missed? Would this bug affect the performance of P-IQL? 

https://github.com/jhejna/cpl/blob/eef949ef693bfb50d008e10ab3332a4faa19b871/research/algs/piql.py#L149

**Comment by jhejna** [comment]
Hi! Thanks for posting this question. I don't believe this is a problem here for the following reasons.
1. Metaworld environments *should* use infinite bootstrapping (this generally increases performance), meaning there is no case where we would want to truncate the value. 
2. This repo was made before the switch to the new Gym API that fixed this problem, so I used my own solution.  I log the discount to the replay buffer as 0 or 1 (see [here](https://github.com/jhejna/cpl/blob/main/research/algs/off_policy_algorithm.py#L108C37-L108C37)), then multiply it by the chosen discount factor value when sampling (see [here](https://github.com/jhejna/cpl/blob/main/research/datasets/replay_buffer/sampling.py#L141))
3. If using a `FeedbackDataset`, there are no terminal states, we don't even sample any terminal states as part of the segments dataset. This is what was used in the PIQL config.

If you want a longer explanation, I would look at the Farma Foundation post on time limits and bootstrapping [here](https://gymnasium.farama.org/tutorials/gymnasium_basics/handling_time_limits/).  Let me know if you have any questions!

**Comment by typoverflow** [comment]
Hi @jhejna, thanks for the explanation. I'm not so familiar with the metaworld environments, but given the fact that it is infinitely bootstrapped (which is strange to me at first since it is a goal-reaching task), I think there is no problem with PIQL. 
Thanks again for your time : )
