### ISSUE TITLE
How to create datasets?

### ISSUE THREAD

**Issue by gyh-ustc** [jhejna/cpl#5]
Could you please tell me how to create the data set from raw data?

**Comment by jhejna** [comment]
Hi! We did the following to create our datasets:

1. Train SAC policies using the`configs/oracle/sac.yaml` configuration file. 
2. Choosing a checkpoint that achieved only around 50% success rate (see Appendix for exact values on each domain), and rolling it out to create a trajectory dataset using `create_dataset.py`. We also added some random gaussian noise.
3. Sampling this into a preference dataset using `create_comparison_dataset.py`.
4. Training another oracle SAC policy to convergence, with the replay buffer initialized to the trajectory dataset. This ensures low bellman error for the advantage estimation.
5. Using this new oracle SAC policy to add preference labels using `add_preference_labels.py`

Alternatively, we provided download links for all of our datasets in the readme.

**Comment by gyh-ustc** [comment]
> Hi! We did the following to create our datasets:
> 
> 1. Train SAC policies using the`configs/oracle/sac.yaml` configuration file.
> 2. Choosing a checkpoint that achieved only around 50% success rate (see Appendix for exact values on each domain), and rolling it out to create a trajectory dataset using `create_dataset.py`. We also added some random gaussian noise.
> 3. Sampling this into a preference dataset using `create_comparison_dataset.py`.
> 4. Training another oracle SAC policy to convergence, with the replay buffer initialized to the trajectory dataset. This ensures low bellman error for the advantage estimation.
> 5. Using this new oracle SAC policy to add preference labels using `add_preference_labels.py`
> 
> Alternatively, we provided download links for all of our datasets in the readme.

Thanks for your reply. It helps a lot.
