### ISSUE TITLE
Nice work!

### ISSUE THREAD

**Issue by pengzhenghao** [jhejna/cpl#8]
Congraduation to this work!

A quick question, what's the difference between this paper and IPL? It seems in the CPL paper IPL is rarely mentioned and compared.

**Comment by jhejna** [comment]
IPL assumes preferences to be distributed according to the reward function, and then does a form of bootstrapping. IPL is not state of the art at preference-based RL (it matches baselines while removing the reward network), so we did not compare against it.

CPL assumes preferences to be distributed according to the optimal advantage function, and thus is able to remove the reward and Q-network. It does not do any bootstrapping.
